version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: dockerfile/api/Dockerfile
      args:
        - DOCKERHUB_URL=243963068353.dkr.ecr.us-west-2.amazonaws.com/
    image: api-server:latest
    command: [
      "/app/api/build/server",
      "--config=/app/api/config/base.yaml,/app/api/config/local-docker.yaml,/app/api/config/secrets.yaml"
    ]
    depends_on:
      - api-database
    ports:
      - "20005:20005"
  streamer:
    build:
      context: .
      dockerfile: dockerfile/api/streamer/Dockerfile
      args:
        - DOCKERHUB_URL=243963068353.dkr.ecr.us-west-2.amazonaws.com/
    image: streamer:latest
    command: [
      "/app/api/build/streamer",
      "--config=/app/api/config/streamer/base.yaml,/app/api/config/streamer/local-docker.yaml,/app/api/config/streamer/secrets.yaml"
    ]
  bastion:
    environment:
      - SERVER_ENV=local-docker
    build:
      context: .
      dockerfile: dockerfile/bastion/Dockerfile
    image: bastion:latest
  api-database:
    image: "postgres:12.4"
    container_name: "api-database"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust # https://andrew.hawker.io/dailies/2020/02/25/postgres-uninitialized-error/
    ports:
      - "23005:5432"