version: '3.7'
services:
  api:
    build:
      # Read Makefile to understand why we want to build from the top-level "." context.
      context: .
      dockerfile: dockerfile/api/Dockerfile
    image: api-server:latest
    command: [
      "/app/api/build/server",
      "--config=/app/api/config/local-docker.yaml"
    ]
    depends_on:
      - api-database
    ports:
      - "20005:20005"
  bastion:
    build:
      # Read Makefile to understand why we want to build from the top-level "." context.
      context: .
      dockerfile: dockerfile/bastion/Dockerfile
    image: bastion:latest
  api-database:
    image: "postgres:12.4"
    container_name: "api-database"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust # https://andrew.hawker.io/dailies/2020/02/25/postgres-uninitialized-error/
    ports:
      - "23005:5432"