apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamer
  namespace: edge
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: streamer
        args:
          - "/app/api/build/streamer"
          - "--config=/app/api/config/streamer/base.yaml,/app/api/config/streamer/dev.yaml"
        env:
          - name: SERVER_ENV
            value: "dev"
        resources:
          requests:
            cpu: "300m"
            memory: "800Mi"
          limits:
            cpu: "500m"
            memory: "1000Mi"