// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/v1/web3_gateway/storage.proto

package web3_gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorageType int32

const (
	StorageType_UNSPECIFIED_STORAGE_TYPE StorageType = 0
	StorageType_ARWEAVE                  StorageType = 1
	StorageType_IPFS                     StorageType = 2
)

// Enum value maps for StorageType.
var (
	StorageType_name = map[int32]string{
		0: "UNSPECIFIED_STORAGE_TYPE",
		1: "ARWEAVE",
		2: "IPFS",
	}
	StorageType_value = map[string]int32{
		"UNSPECIFIED_STORAGE_TYPE": 0,
		"ARWEAVE":                  1,
		"IPFS":                     2,
	}
)

func (x StorageType) Enum() *StorageType {
	p := new(StorageType)
	*p = x
	return p
}

func (x StorageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_web3_gateway_storage_proto_enumTypes[0].Descriptor()
}

func (StorageType) Type() protoreflect.EnumType {
	return &file_proto_v1_web3_gateway_storage_proto_enumTypes[0]
}

func (x StorageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageType.Descriptor instead.
func (StorageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_web3_gateway_storage_proto_rawDescGZIP(), []int{0}
}

type ContentType int32

const (
	ContentType_UNSPECIFIED_CONTENT_TYPE ContentType = 0
	ContentType_MARKDOWN                 ContentType = 1
)

// Enum value maps for ContentType.
var (
	ContentType_name = map[int32]string{
		0: "UNSPECIFIED_CONTENT_TYPE",
		1: "MARKDOWN",
	}
	ContentType_value = map[string]int32{
		"UNSPECIFIED_CONTENT_TYPE": 0,
		"MARKDOWN":                 1,
	}
)

func (x ContentType) Enum() *ContentType {
	p := new(ContentType)
	*p = x
	return p
}

func (x ContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v1_web3_gateway_storage_proto_enumTypes[1].Descriptor()
}

func (ContentType) Type() protoreflect.EnumType {
	return &file_proto_v1_web3_gateway_storage_proto_enumTypes[1]
}

func (x ContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentType.Descriptor instead.
func (ContentType) EnumDescriptor() ([]byte, []int) {
	return file_proto_v1_web3_gateway_storage_proto_rawDescGZIP(), []int{1}
}

type Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Tag) Reset() {
	*x = Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_web3_gateway_storage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_web3_gateway_storage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_proto_v1_web3_gateway_storage_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UploadContentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Storage     StorageType `protobuf:"varint,1,opt,name=storage,proto3,enum=web3_gateway.StorageType" json:"storage,omitempty"`
	Content     []byte      `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ContentType ContentType `protobuf:"varint,3,opt,name=content_type,json=contentType,proto3,enum=web3_gateway.ContentType" json:"content_type,omitempty"`
	Tags        []*Tag      `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *UploadContentReq) Reset() {
	*x = UploadContentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_web3_gateway_storage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadContentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadContentReq) ProtoMessage() {}

func (x *UploadContentReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_web3_gateway_storage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadContentReq.ProtoReflect.Descriptor instead.
func (*UploadContentReq) Descriptor() ([]byte, []int) {
	return file_proto_v1_web3_gateway_storage_proto_rawDescGZIP(), []int{1}
}

func (x *UploadContentReq) GetStorage() StorageType {
	if x != nil {
		return x.Storage
	}
	return StorageType_UNSPECIFIED_STORAGE_TYPE
}

func (x *UploadContentReq) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UploadContentReq) GetContentType() ContentType {
	if x != nil {
		return x.ContentType
	}
	return ContentType_UNSPECIFIED_CONTENT_TYPE
}

func (x *UploadContentReq) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type UploadContentResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContentUrl string `protobuf:"bytes,1,opt,name=content_url,json=contentUrl,proto3" json:"content_url,omitempty"`
}

func (x *UploadContentResp) Reset() {
	*x = UploadContentResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_web3_gateway_storage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadContentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadContentResp) ProtoMessage() {}

func (x *UploadContentResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_web3_gateway_storage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadContentResp.ProtoReflect.Descriptor instead.
func (*UploadContentResp) Descriptor() ([]byte, []int) {
	return file_proto_v1_web3_gateway_storage_proto_rawDescGZIP(), []int{2}
}

func (x *UploadContentResp) GetContentUrl() string {
	if x != nil {
		return x.ContentUrl
	}
	return ""
}

var File_proto_v1_web3_gateway_storage_proto protoreflect.FileDescriptor

var file_proto_v1_web3_gateway_storage_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x65, 0x62, 0x33, 0x5f,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x77, 0x65, 0x62, 0x33, 0x5f, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x22, 0x2f, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0xc6, 0x01, 0x0a, 0x10, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x33, 0x0a, 0x07, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x77, 0x65, 0x62,
	0x33, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x3c, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19,
	0x2e, 0x77, 0x65, 0x62, 0x33, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x77, 0x65, 0x62, 0x33, 0x5f, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x34, 0x0a,
	0x11, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x55, 0x72, 0x6c, 0x2a, 0x42, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1c, 0x0a, 0x18, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x5f, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x41, 0x52, 0x57, 0x45, 0x41, 0x56, 0x45, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x49, 0x50, 0x46, 0x53, 0x10, 0x02, 0x2a, 0x39, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x18, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x41, 0x52, 0x4b, 0x44, 0x4f, 0x57, 0x4e,
	0x10, 0x01, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2d, 0x6e, 0x6f, 0x76, 0x61, 0x2f, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x77,
	0x65, 0x62, 0x33, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_v1_web3_gateway_storage_proto_rawDescOnce sync.Once
	file_proto_v1_web3_gateway_storage_proto_rawDescData = file_proto_v1_web3_gateway_storage_proto_rawDesc
)

func file_proto_v1_web3_gateway_storage_proto_rawDescGZIP() []byte {
	file_proto_v1_web3_gateway_storage_proto_rawDescOnce.Do(func() {
		file_proto_v1_web3_gateway_storage_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_v1_web3_gateway_storage_proto_rawDescData)
	})
	return file_proto_v1_web3_gateway_storage_proto_rawDescData
}

var file_proto_v1_web3_gateway_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_v1_web3_gateway_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_v1_web3_gateway_storage_proto_goTypes = []interface{}{
	(StorageType)(0),          // 0: web3_gateway.StorageType
	(ContentType)(0),          // 1: web3_gateway.ContentType
	(*Tag)(nil),               // 2: web3_gateway.Tag
	(*UploadContentReq)(nil),  // 3: web3_gateway.UploadContentReq
	(*UploadContentResp)(nil), // 4: web3_gateway.UploadContentResp
}
var file_proto_v1_web3_gateway_storage_proto_depIdxs = []int32{
	0, // 0: web3_gateway.UploadContentReq.storage:type_name -> web3_gateway.StorageType
	1, // 1: web3_gateway.UploadContentReq.content_type:type_name -> web3_gateway.ContentType
	2, // 2: web3_gateway.UploadContentReq.tags:type_name -> web3_gateway.Tag
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_v1_web3_gateway_storage_proto_init() }
func file_proto_v1_web3_gateway_storage_proto_init() {
	if File_proto_v1_web3_gateway_storage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_v1_web3_gateway_storage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_web3_gateway_storage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadContentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_web3_gateway_storage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadContentResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_v1_web3_gateway_storage_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_web3_gateway_storage_proto_goTypes,
		DependencyIndexes: file_proto_v1_web3_gateway_storage_proto_depIdxs,
		EnumInfos:         file_proto_v1_web3_gateway_storage_proto_enumTypes,
		MessageInfos:      file_proto_v1_web3_gateway_storage_proto_msgTypes,
	}.Build()
	File_proto_v1_web3_gateway_storage_proto = out.File
	file_proto_v1_web3_gateway_storage_proto_rawDesc = nil
	file_proto_v1_web3_gateway_storage_proto_goTypes = nil
	file_proto_v1_web3_gateway_storage_proto_depIdxs = nil
}
