---
apiVersion: v1
kind: Service
metadata:
  namespace: web3 
  name: web3-gateway-service 
  labels:
    app: storyprotocol 
    service: web3-gateway-service 
spec:
  ports:
  - name: web3-gateway-service 
    port: 8090
    targetPort: 8090
  type: NodePort
  selector:
    service: web3-gateway-service 
---
