apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- patch.yaml
resources:
- ../../base
#- name: 243963068353.dkr.ecr.us-west-2.amazonaws.com/bastion
#  newName: 243963068353.dkr.ecr.us-west-2.amazonaws.com/bastion
images:
- name: 243963068353.dkr.ecr.us-east-2.amazonaws.com/bastion
  newName: 243963068353.dkr.ecr.us-east-2.amazonaws.com/bastion
  newTag: latest
