---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: edge 
  name: api
  labels:
    app: storyprotocol
    service: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      service: api-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  minReadySeconds: 2
  template:
    metadata:
      labels:
        service: api-server
    spec:
      containers:
      - image: 243963068353.dkr.ecr.us-east-2.amazonaws.com/api:latest
        imagePullPolicy: "Always"
        name: api
        ports:
        - containerPort: 8090